# Generated by Django 3.2.13 on 2022-04-18 08:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Home About Section',
                'verbose_name_plural': 'Home About Section',
            },
        ),
        migrations.CreateModel(
            name='HomeLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo/')),
            ],
            options={
                'verbose_name': 'Home Logo',
                'verbose_name_plural': 'Home Logo',
            },
        ),
        migrations.CreateModel(
            name='HomeTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, upload_to='video/', verbose_name='Background Video')),
                ('image', models.ImageField(blank=True, upload_to='image/logo/', verbose_name='Logo image')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(max_length=1000)),
                ('button', models.TextField(max_length=300)),
                ('button_link', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Home Title',
                'verbose_name_plural': 'Home Title',
            },
        ),
    ]
